// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Russian.Post.Database.Contexts;

namespace Russian.Post.Database.Migrations.RussianPostMigrations
{
    [DbContext(typeof(RussianPostContext))]
    [Migration("20190922162633_AlterTablePostClientMessageAddIsDelivered")]
    partial class AlterTablePostClientMessageAddIsDelivered
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Russian.Post.Database.Models.PostClientMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AttemptCount");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsDelivered");

                    b.Property<string>("Message")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.ToTable("PostClientMessages");
                });

            modelBuilder.Entity("Russian.Post.Database.Models.PostServerMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<string>("IpAddress");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Message")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.ToTable("PostServerMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
